mysql:
  host: 154.12.41.116
  port: 3306
  username: root
  password: 775345
  database: User_Information
minio:
  endpoint: 154.12.41.116:9000
  access1ID: 4BdCx4u9PTIgzd0i2uLA
  access2Key: MJlxPe5hTyB1thHWwOqFRjJTsLuCIp11ONuuwuHa
  bucket: gwq
  accessID: DIqPKbAVO8vAzm3YbQee
  accessKey: oPQFd4oQwALsiiVHtm6yvcYsmlQmDRHuilRhU5vW
  bucket1: gwq

#service
server:
  port: 8088

websocket:
  ip: 127.0.0.1 #运行部署要换成公网ip
  port: 8089
  rpcPort: 8090

redis:
  masteraddr: 154.12.41.116:6379
  password: 775345
  DB: 0
